title: "Portfolio - Thibault PERNEL"
email: "thibaultpernel@gmail.com"
description: "Développeur Full Stack passionné par la création d'applications innovantes"
baseurl: ""
url: "https://pralexio.github.io/"
twitter_username: "Pralexio"
github_username: "Pralexio"

# Désactivation du thème par défaut
theme: null

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed

markdown: kramdown
highlighter: rouge

paginate: 6
paginate_path: "/blog/page:num/"

# Personnalisation du thème
logo: /assets/img/logo.png
show_downloads: false

